enum ProductsCategories {
  FASHION_AND_APPAREL,
  HOME_AND_LIVING,
  HEALTH_AND_WELLNESS,
  BABY_AND_KIDS,
  BOOKS_AND_STATIONERY,
  ELECTRONICS_AND_GADGETS,
  BEAUTY_AND_PERSONAL_CARE,
  FOOD,
  AUTOMOBILE_AND_ACCESSORIES,
  SPORTS_AND_OUTDOOR,
  SERVICES,
  OTHERS,
}

enum FoodCategories {
  BREAKFAST,
  LUNCH,
  DINNER,
  SNACKS,
  DESSERTS,
  DRINKS,
  FAST_FOOD,
  LOCAL,
  OTHERS,
}
